const { convertToMarkdown, fetchAndConvertDoc, updateGitHubFile } = require('../../scripts/docs-sync/sync-google-doc');
const fs = require('fs').promises;
const path = require('path');

describe('Google Docs Sync', () => {
  describe('convertToMarkdown', () => {
    test('should convert simple text to markdown', () => {
      const content = {
        body: {
          content: [
            {
              paragraph: {
                elements: [
                  {
                    textRun: {
                      content: 'Hello World\n'
                    }
                  }
                ]
              }
            }
          ]
        }
      };

      const result = convertToMarkdown(content);
      expect(result).toBe('Hello World');
    });

    test('should convert headers to markdown', () => {
      const content = {
        body: {
          content: [
            {
              paragraph: {
                elements: [
                  {
                    textRun: {
                      content: 'Main Title\n'
                    }
                  }
                ],
                paragraphStyle: {
                  namedStyleType: 'HEADING_1'
                }
              }
            }
          ]
        }
      };

      const result = convertToMarkdown(content);
      expect(result).toBe('# Main Title');
    });

    test('should convert bold text to markdown', () => {
      const content = {
        body: {
          content: [
            {
              paragraph: {
                elements: [
                  {
                    textRun: {
                      content: 'Bold text',
                      textStyle: {
                        bold: true
                      }
                    }
                  }
                ]
              }
            }
          ]
        }
      };

      const result = convertToMarkdown(content);
      expect(result).toBe('**Bold text**');
    });

    test('should convert italic text to markdown', () => {
      const content = {
        body: {
          content: [
            {
              paragraph: {
                elements: [
                  {
                    textRun: {
                      content: 'Italic text',
                      textStyle: {
                        italic: true
                      }
                    }
                  }
                ]
              }
            }
          ]
        }
      };

      const result = convertToMarkdown(content);
      expect(result).toBe('*Italic text*');
    });

    test('should convert links to markdown', () => {
      const content = {
        body: {
          content: [
            {
              paragraph: {
                elements: [
                  {
                    textRun: {
                      content: 'Click here',
                      textStyle: {
                        link: {
                          url: 'https://example.com'
                        }
                      }
                    }
                  }
                ]
              }
            }
          ]
        }
      };

      const result = convertToMarkdown(content);
      expect(result).toBe('[Click here](https://example.com)');
    });

    test('should handle empty content', () => {
      const content = null;
      const result = convertToMarkdown(content);
      expect(result).toBe('');
    });
  });

  describe('updateGitHubFile', () => {
    const testDir = '/tmp/test-docs-sync';
    const testFile = path.join(testDir, 'test.md');

    beforeEach(async () => {
      await fs.mkdir(testDir, { recursive: true });
    });

    afterEach(async () => {
      try {
        await fs.rm(testDir, { recursive: true });
      } catch (error) {
        // Ignore cleanup errors
      }
    });

    test('should create file with metadata header', async () => {
      const content = 'Test content';
      await updateGitHubFile(testFile, content);

      const fileContent = await fs.readFile(testFile, 'utf8');
      expect(fileContent).toContain('<!-- Auto-generated from Google Docs');
      expect(fileContent).toContain('<!-- Do not edit this file directly');
      expect(fileContent).toContain('Test content');
    });

    test('should create directory if it does not exist', async () => {
      const nestedFile = path.join(testDir, 'nested', 'dir', 'test.md');
      const content = 'Nested test content';
      
      await updateGitHubFile(nestedFile, content);
      
      const fileContent = await fs.readFile(nestedFile, 'utf8');
      expect(fileContent).toContain('Nested test content');
    });
  });
});